AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

